// <auto-generated />
namespace StudentLecture.Migrations.AttendMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SetIdentityNone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetIdentityNone));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101411267_SetIdentityNone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
